package com.framework.data;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;

/**
 * JSON Data Provider - Reads element locators and action details from JSON files
 * Generated by Playwright agent execution
 */
public class JsonDataProvider {
    private static final Logger logger = LoggerFactory.getLogger(JsonDataProvider.class);

    /**
     * Get element locators for a specific Gherkin step
     * Priority: 1) Feature JSON, 2) Step Repository, 3) Shared Libraries
     */
    public static ElementLocators getLocatorsForStep(String featureName, String gherkinStep) {
        logger.debug("Checking step repository for: {}", gherkinStep);
        
        // 1. Check Step Repository (individual step files)
        ElementLocators repoLocators = StepRepository.getLocators(gherkinStep);
        if (repoLocators != null) {
            return repoLocators;
        }
        
        logger.debug("Step not found in repository, checking shared libraries for: {}", gherkinStep);
        
        // 2. Fallback to shared steps libraries
        List<String> sharedLibraries = Arrays.asList("common-login", "common-navigation", "common-actions");
        for (String library : sharedLibraries) {
            ElementLocators locators = SharedStepsProvider.getLocatorsFromSharedStep(library, gherkinStep);
            if (locators != null) {
                logger.info("[OK] Found step in shared library: {}", library);
                return locators;
            }
        }
        
        logger.debug("No matching step found in any source for: {}", gherkinStep);
        return null;
    }
    
    /**
     * Get all actions for a specific step
     * Priority: 1) Step Repository, 2) Shared Libraries
     */
    public static List<ActionData> getActionsForStep(String featureName, String gherkinStep) {
        logger.debug("Checking cache for step: {}", gherkinStep);
        
        // 1. Check Step Repository (individual step files)
        List<ActionData> repoActions = StepRepository.getActions(gherkinStep);
        if (!repoActions.isEmpty()) {
            return repoActions;
        }
        
        logger.debug("Step not found in repository, checking shared libraries for: {}", gherkinStep);
        
        // 2. Fallback to shared steps libraries
        List<String> sharedLibraries = Arrays.asList("common-login", "common-navigation", "common-actions");
        for (String library : sharedLibraries) {
            List<ActionData> actions = SharedStepsProvider.getActionsFromSharedStep(library, gherkinStep);
            if (!actions.isEmpty()) {
                logger.info("[OK] Found step in shared library: {}", library);
                return actions;
            }
        }
        
        return Collections.emptyList();
    }
    
    
    /**
     * Normalize step text for comparison
     */
    private static String normalizeStepText(String stepText) {
        return stepText
            .replaceAll("^(Given|When|Then|And|But)\\s+", "")
            .replaceAll("\"", "'")
            .trim()
            .toLowerCase();
    }
    
}
